// features/records/domain/models/record_model.dart

import 'package:hive/hive.dart';

part 'record_model.g.dart'; // This will be generated by hive_generator

@HiveType(typeId: 0)
class RecordModel extends HiveObject {
  @HiveField(0)
  final String id;
  
  @HiveField(1)
  final String type; // e.g., 'feeding', 'sleep', 'urination', 'stool', 'diaper'
  
  @HiveField(2)
  final DateTime timestamp;
  
  @HiveField(3)
  final Map<String, dynamic> metadata; // Dynamic data for specific types (e.g., feedingType: 'left')
  
  @HiveField(4)
  final bool isSynced; // Flag for background sync engine
  
  RecordModel({
    required this.id,
    required this.type,
    required this.timestamp,
    this.metadata = const {},
    this.isSynced = false,
  });

  RecordModel copyWith({
    String? id,
    String? type,
    DateTime? timestamp,
    Map<String, dynamic>? metadata,
    bool? isSynced,
  }) {
    return RecordModel(
      id: id ?? this.id,
      type: type ?? this.type,
      timestamp: timestamp ?? this.timestamp,
      metadata: metadata ?? this.metadata,
      isSynced: isSynced ?? this.isSynced,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'type': type,
      'timestamp': timestamp.toIso8601String(),
      'metadata': metadata,
      'isSynced': isSynced,
    };
  }

  factory RecordModel.fromJson(Map<String, dynamic> json) {
    return RecordModel(
      id: json['id'] as String,
      type: json['type'] as String,
      timestamp: DateTime.parse(json['timestamp'] as String),
      metadata: Map<String, dynamic>.from(json['metadata'] ?? {}),
      isSynced: json['isSynced'] as bool? ?? false,
    );
  }

  Map<String, dynamic> toFirestore() {
    return {
      'id': id,
      'type': type,
      'timestamp': timestamp.toIso8601String(),
      'metadata': metadata,
    };
  }

  factory RecordModel.fromFirestore(Map<String, dynamic> json) {
    return RecordModel(
      id: json['id'] as String,
      type: json['type'] as String,
      timestamp: DateTime.parse(json['timestamp'] as String),
      metadata: Map<String, dynamic>.from(json['metadata'] ?? {}),
      isSynced: true,
    );
  }
}
